package com.hcx.medhistory.mapping;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Collections;

/**
 * One normalized database row. Keys in {@code columns} are the column names in
 * medication_history_populations_postgresql.sql.
 *
 * Values may contain {@link FhirKey} in a foreign-key column. A persistence
 * adapter resolves that key to the BIGINT generated by PostgreSQL. Keeping the
 * reference intact is important: the incoming Bundle may list resources in any
 * order, so numeric database keys do not exist while parsing.
 */
public record TableRow(String table, Map<String, Object> columns) {
    public TableRow {
        Objects.requireNonNull(table, "table");
        // SQL rows legitimately contain nulls; Map.copyOf would reject them.
        columns = Collections.unmodifiableMap(new LinkedHashMap<>(columns));
    }
}
