-- HDC-230: Relax all NOT NULL and FK constraints on the fhir schema.
-- Run against QA and prod before the next import run.
-- DROP CONSTRAINT uses IF EXISTS; DROP NOT NULL is a no-op on already-nullable columns.

BEGIN;

-- ── Drop NOT NULL constraints ────────────────────────────────────────────────
ALTER TABLE fhir.bundle ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.bundle ALTER COLUMN bundle_type DROP NOT NULL;
ALTER TABLE fhir.bundle ALTER COLUMN received_at DROP NOT NULL;
ALTER TABLE fhir.bundle_link ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.bundle_link ALTER COLUMN relation DROP NOT NULL;
ALTER TABLE fhir.bundle_link ALTER COLUMN url DROP NOT NULL;
ALTER TABLE fhir.bundle_link ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.bundle_resource ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.bundle_resource ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.bundle_resource ALTER COLUMN resource_type DROP NOT NULL;
ALTER TABLE fhir.bundle_resource ALTER COLUMN resource_fhir_id DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN active DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN gender DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN birth_date DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.patient ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.organization ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.organization ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.organization ALTER COLUMN active DROP NOT NULL;
ALTER TABLE fhir.organization ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.organization ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.practitioner ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.practitioner ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.practitioner ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.practitioner ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.medication ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.medication ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.medication ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.condition ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.condition ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.condition ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.condition ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN status DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN intent DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN medication_id DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN requester_practitioner_id DROP NOT NULL; -- HDC-230: missing from initial narrow fix
ALTER TABLE fhir.medication_request ALTER COLUMN authored_on DROP NOT NULL;             -- HDC-230: missing from initial narrow fix
ALTER TABLE fhir.medication_request ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.medication_request ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.medication_request_performer ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_request_performer ALTER COLUMN medication_request_id DROP NOT NULL;
ALTER TABLE fhir.medication_request_performer ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE fhir.medication_request_performer ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN status DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN medication_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN quantity_value DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN days_supply_value DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN when_prepared DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_performer ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_performer ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_performer ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_performer ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_prescription ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_prescription ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_prescription ALTER COLUMN medication_request_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_prescription ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_type_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_type_coding ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_type_coding ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_dosage_instruction ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_dosage_instruction ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_dosage_instruction ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_extension ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_extension ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_extension ALTER COLUMN url DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_extension ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN fhir_id DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN status DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN received DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN search_mode DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN meta_version_id DROP NOT NULL;
ALTER TABLE fhir.communication ALTER COLUMN meta_last_updated DROP NOT NULL;
ALTER TABLE fhir.communication_based_on ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication_based_on ALTER COLUMN communication_id DROP NOT NULL;
ALTER TABLE fhir.communication_based_on ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.communication_category_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication_category_coding ALTER COLUMN communication_id DROP NOT NULL;
ALTER TABLE fhir.communication_category_coding ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.communication_reason_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication_reason_coding ALTER COLUMN communication_id DROP NOT NULL;
ALTER TABLE fhir.communication_reason_coding ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.communication_extension ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication_extension ALTER COLUMN communication_id DROP NOT NULL;
ALTER TABLE fhir.communication_extension ALTER COLUMN url DROP NOT NULL;
ALTER TABLE fhir.communication_extension ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.patient_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.patient_identifier ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.patient_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.patient_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.organization_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.organization_identifier ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE fhir.organization_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.organization_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.practitioner_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_identifier ALTER COLUMN practitioner_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.practitioner_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.medication_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_identifier ALTER COLUMN medication_id DROP NOT NULL;
ALTER TABLE fhir.medication_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.medication_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.condition_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.condition_identifier ALTER COLUMN condition_id DROP NOT NULL;
ALTER TABLE fhir.condition_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.condition_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.medication_request_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_request_identifier ALTER COLUMN medication_request_id DROP NOT NULL;
ALTER TABLE fhir.medication_request_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.medication_request_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_identifier ALTER COLUMN medication_dispense_id DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.medication_dispense_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.communication_identifier ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.communication_identifier ALTER COLUMN communication_id DROP NOT NULL;
ALTER TABLE fhir.communication_identifier ALTER COLUMN use_code DROP NOT NULL;
ALTER TABLE fhir.communication_identifier ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.patient_name ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.patient_name ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.patient_name ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.practitioner_name ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_name ALTER COLUMN practitioner_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_name ALTER COLUMN ordinal DROP NOT NULL;
ALTER TABLE fhir.patient_telecom ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.patient_telecom ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.patient_telecom ALTER COLUMN system_code DROP NOT NULL;
ALTER TABLE fhir.organization_telecom ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.organization_telecom ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE fhir.organization_telecom ALTER COLUMN system_code DROP NOT NULL;
ALTER TABLE fhir.practitioner_telecom ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_telecom ALTER COLUMN practitioner_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_telecom ALTER COLUMN system_code DROP NOT NULL;
ALTER TABLE fhir.patient_address ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.patient_address ALTER COLUMN patient_id DROP NOT NULL;
ALTER TABLE fhir.patient_address ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.organization_address ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.organization_address ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE fhir.organization_address ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.practitioner_address ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_address ALTER COLUMN practitioner_id DROP NOT NULL;
ALTER TABLE fhir.practitioner_address ALTER COLUMN period_start DROP NOT NULL;
ALTER TABLE fhir.medication_code_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.medication_code_coding ALTER COLUMN medication_id DROP NOT NULL;
ALTER TABLE fhir.medication_code_coding ALTER COLUMN system_uri DROP NOT NULL;
ALTER TABLE fhir.condition_code_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.condition_code_coding ALTER COLUMN condition_id DROP NOT NULL;
ALTER TABLE fhir.condition_code_coding ALTER COLUMN system_uri DROP NOT NULL;
ALTER TABLE fhir.condition_category_coding ALTER COLUMN bundle_id DROP NOT NULL;
ALTER TABLE fhir.condition_category_coding ALTER COLUMN condition_id DROP NOT NULL;
ALTER TABLE fhir.condition_category_coding ALTER COLUMN system_uri DROP NOT NULL;

-- ── Drop named FK constraints ────────────────────────────────────────────────
ALTER TABLE fhir.bundle DROP CONSTRAINT IF EXISTS fk_condition_patient;
ALTER TABLE fhir.medication_request DROP CONSTRAINT IF EXISTS fk_medreq_medication;
ALTER TABLE fhir.medication_request_performer DROP CONSTRAINT IF EXISTS fk_meddisp_medication;
ALTER TABLE fhir.medication_dispense_performer DROP CONSTRAINT IF EXISTS fk_communication_patient;
ALTER TABLE fhir.communication_based_on DROP CONSTRAINT IF EXISTS fk_comm_based_on_meddisp;

-- ── Drop inline (auto-named) FK constraints ──────────────────────────────────
ALTER TABLE fhir.bundle_link DROP CONSTRAINT IF EXISTS bundle_link_bundle_id_fkey;
ALTER TABLE fhir.bundle_resource DROP CONSTRAINT IF EXISTS bundle_resource_bundle_id_fkey;
ALTER TABLE fhir.patient DROP CONSTRAINT IF EXISTS patient_bundle_id_fkey;
ALTER TABLE fhir.organization DROP CONSTRAINT IF EXISTS organization_bundle_id_fkey;
ALTER TABLE fhir.practitioner DROP CONSTRAINT IF EXISTS practitioner_bundle_id_fkey;
ALTER TABLE fhir.medication DROP CONSTRAINT IF EXISTS medication_bundle_id_fkey;
ALTER TABLE fhir.condition DROP CONSTRAINT IF EXISTS condition_bundle_id_fkey;
ALTER TABLE fhir.medication_request DROP CONSTRAINT IF EXISTS medication_request_bundle_id_fkey;
ALTER TABLE fhir.medication_request_performer DROP CONSTRAINT IF EXISTS medication_request_performer_bundle_id_fkey;
ALTER TABLE fhir.medication_request_performer DROP CONSTRAINT IF EXISTS medication_request_performer_medication_request_id_fkey;
ALTER TABLE fhir.medication_request_performer DROP CONSTRAINT IF EXISTS medication_request_performer_organization_id_fkey;
ALTER TABLE fhir.medication_dispense DROP CONSTRAINT IF EXISTS medication_dispense_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_performer DROP CONSTRAINT IF EXISTS medication_dispense_performer_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_performer DROP CONSTRAINT IF EXISTS medication_dispense_performer_medication_dispense_id_fkey;
ALTER TABLE fhir.medication_dispense_performer DROP CONSTRAINT IF EXISTS medication_dispense_performer_organization_id_fkey;
ALTER TABLE fhir.medication_dispense_prescription DROP CONSTRAINT IF EXISTS medication_dispense_prescription_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_prescription DROP CONSTRAINT IF EXISTS medication_dispense_prescription_medication_dispense_id_fkey;
ALTER TABLE fhir.medication_dispense_prescription DROP CONSTRAINT IF EXISTS medication_dispense_prescription_medication_request_id_fkey;
ALTER TABLE fhir.medication_dispense_type_coding DROP CONSTRAINT IF EXISTS medication_dispense_type_coding_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_type_coding DROP CONSTRAINT IF EXISTS medication_dispense_type_coding_medication_dispense_id_fkey;
ALTER TABLE fhir.medication_dispense_dosage_instruction DROP CONSTRAINT IF EXISTS medication_dispense_dosage_instruction_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_dosage_instruction DROP CONSTRAINT IF EXISTS medication_dispense_dosage_instruction_medication_dispense_id_fkey;
ALTER TABLE fhir.medication_dispense_extension DROP CONSTRAINT IF EXISTS medication_dispense_extension_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_extension DROP CONSTRAINT IF EXISTS medication_dispense_extension_medication_dispense_id_fkey;
ALTER TABLE fhir.communication DROP CONSTRAINT IF EXISTS communication_bundle_id_fkey;
ALTER TABLE fhir.communication_based_on DROP CONSTRAINT IF EXISTS communication_based_on_bundle_id_fkey;
ALTER TABLE fhir.communication_based_on DROP CONSTRAINT IF EXISTS communication_based_on_communication_id_fkey;
ALTER TABLE fhir.communication_category_coding DROP CONSTRAINT IF EXISTS communication_category_coding_bundle_id_fkey;
ALTER TABLE fhir.communication_category_coding DROP CONSTRAINT IF EXISTS communication_category_coding_communication_id_fkey;
ALTER TABLE fhir.communication_reason_coding DROP CONSTRAINT IF EXISTS communication_reason_coding_bundle_id_fkey;
ALTER TABLE fhir.communication_reason_coding DROP CONSTRAINT IF EXISTS communication_reason_coding_communication_id_fkey;
ALTER TABLE fhir.communication_extension DROP CONSTRAINT IF EXISTS communication_extension_bundle_id_fkey;
ALTER TABLE fhir.communication_extension DROP CONSTRAINT IF EXISTS communication_extension_communication_id_fkey;
ALTER TABLE fhir.patient_identifier DROP CONSTRAINT IF EXISTS patient_identifier_bundle_id_fkey;
ALTER TABLE fhir.patient_identifier DROP CONSTRAINT IF EXISTS patient_identifier_patient_id_fkey;
ALTER TABLE fhir.organization_identifier DROP CONSTRAINT IF EXISTS organization_identifier_bundle_id_fkey;
ALTER TABLE fhir.organization_identifier DROP CONSTRAINT IF EXISTS organization_identifier_organization_id_fkey;
ALTER TABLE fhir.practitioner_identifier DROP CONSTRAINT IF EXISTS practitioner_identifier_bundle_id_fkey;
ALTER TABLE fhir.practitioner_identifier DROP CONSTRAINT IF EXISTS practitioner_identifier_practitioner_id_fkey;
ALTER TABLE fhir.medication_identifier DROP CONSTRAINT IF EXISTS medication_identifier_bundle_id_fkey;
ALTER TABLE fhir.medication_identifier DROP CONSTRAINT IF EXISTS medication_identifier_medication_id_fkey;
ALTER TABLE fhir.condition_identifier DROP CONSTRAINT IF EXISTS condition_identifier_bundle_id_fkey;
ALTER TABLE fhir.condition_identifier DROP CONSTRAINT IF EXISTS condition_identifier_condition_id_fkey;
ALTER TABLE fhir.medication_request_identifier DROP CONSTRAINT IF EXISTS medication_request_identifier_bundle_id_fkey;
ALTER TABLE fhir.medication_request_identifier DROP CONSTRAINT IF EXISTS medication_request_identifier_medication_request_id_fkey;
ALTER TABLE fhir.medication_dispense_identifier DROP CONSTRAINT IF EXISTS medication_dispense_identifier_bundle_id_fkey;
ALTER TABLE fhir.medication_dispense_identifier DROP CONSTRAINT IF EXISTS medication_dispense_identifier_medication_dispense_id_fkey;
ALTER TABLE fhir.communication_identifier DROP CONSTRAINT IF EXISTS communication_identifier_bundle_id_fkey;
ALTER TABLE fhir.communication_identifier DROP CONSTRAINT IF EXISTS communication_identifier_communication_id_fkey;
ALTER TABLE fhir.patient_name DROP CONSTRAINT IF EXISTS patient_name_bundle_id_fkey;
ALTER TABLE fhir.patient_name DROP CONSTRAINT IF EXISTS patient_name_patient_id_fkey;
ALTER TABLE fhir.practitioner_name DROP CONSTRAINT IF EXISTS practitioner_name_bundle_id_fkey;
ALTER TABLE fhir.practitioner_name DROP CONSTRAINT IF EXISTS practitioner_name_practitioner_id_fkey;
ALTER TABLE fhir.patient_telecom DROP CONSTRAINT IF EXISTS patient_telecom_bundle_id_fkey;
ALTER TABLE fhir.patient_telecom DROP CONSTRAINT IF EXISTS patient_telecom_patient_id_fkey;
ALTER TABLE fhir.organization_telecom DROP CONSTRAINT IF EXISTS organization_telecom_bundle_id_fkey;
ALTER TABLE fhir.organization_telecom DROP CONSTRAINT IF EXISTS organization_telecom_organization_id_fkey;
ALTER TABLE fhir.practitioner_telecom DROP CONSTRAINT IF EXISTS practitioner_telecom_bundle_id_fkey;
ALTER TABLE fhir.practitioner_telecom DROP CONSTRAINT IF EXISTS practitioner_telecom_practitioner_id_fkey;
ALTER TABLE fhir.patient_address DROP CONSTRAINT IF EXISTS patient_address_bundle_id_fkey;
ALTER TABLE fhir.patient_address DROP CONSTRAINT IF EXISTS patient_address_patient_id_fkey;
ALTER TABLE fhir.organization_address DROP CONSTRAINT IF EXISTS organization_address_bundle_id_fkey;
ALTER TABLE fhir.organization_address DROP CONSTRAINT IF EXISTS organization_address_organization_id_fkey;
ALTER TABLE fhir.practitioner_address DROP CONSTRAINT IF EXISTS practitioner_address_bundle_id_fkey;
ALTER TABLE fhir.practitioner_address DROP CONSTRAINT IF EXISTS practitioner_address_practitioner_id_fkey;
ALTER TABLE fhir.medication_code_coding DROP CONSTRAINT IF EXISTS medication_code_coding_bundle_id_fkey;
ALTER TABLE fhir.medication_code_coding DROP CONSTRAINT IF EXISTS medication_code_coding_medication_id_fkey;
ALTER TABLE fhir.condition_code_coding DROP CONSTRAINT IF EXISTS condition_code_coding_bundle_id_fkey;
ALTER TABLE fhir.condition_code_coding DROP CONSTRAINT IF EXISTS condition_code_coding_condition_id_fkey;
ALTER TABLE fhir.condition_category_coding DROP CONSTRAINT IF EXISTS condition_category_coding_bundle_id_fkey;
ALTER TABLE fhir.condition_category_coding DROP CONSTRAINT IF EXISTS condition_category_coding_condition_id_fkey;

COMMIT;
